//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdminEntities : DbContext
    {
        public AdminEntities()
            : base("name=AdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PLATFORM_DEPARTMENT> PLATFORM_DEPARTMENT { get; set; }
        public virtual DbSet<SYS_BUG_FEEDBACK> SYS_BUG_FEEDBACK { get; set; }
        public virtual DbSet<SYS_BUTTON> SYS_BUTTON { get; set; }
        public virtual DbSet<SYS_LOGIN> SYS_LOGIN { get; set; }
        public virtual DbSet<SYS_LOGIN_LOG> SYS_LOGIN_LOG { get; set; }
        public virtual DbSet<SYS_MENU> SYS_MENU { get; set; }
        public virtual DbSet<SYS_OPERATE_LOG> SYS_OPERATE_LOG { get; set; }
        public virtual DbSet<SYS_ROLE> SYS_ROLE { get; set; }
        public virtual DbSet<SYS_ROLE_USER> SYS_ROLE_USER { get; set; }
        public virtual DbSet<SYS_USER> SYS_USER { get; set; }
        public virtual DbSet<SYS_MENU_BUTTON> SYS_MENU_BUTTON { get; set; }
        public virtual DbSet<SYS_ROLE_MENU_BUTTON> SYS_ROLE_MENU_BUTTON { get; set; }
    }
}
