//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_OPERATE_LOG
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserIp { get; set; }
        public string OperateInfo { get; set; }
        public string OperateDesc { get; set; }
        public string Success { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
    }
}
