//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PARAM
    {
        public int ID { get; set; }
        public string TYPE_CODE { get; set; }
        public string PRM_Val_NAME_CH { get; set; }
        public string PRM_Val_NAME_EN { get; set; }
        public string PRM_Val_CODE { get; set; }
        public string RESERVED_1 { get; set; }
        public string RESERVED_2 { get; set; }
        public string RESERVED_3 { get; set; }
    }
}
