//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_CONFIG
    {
        public int ID { get; set; }
        public string SystemName { get; set; }
        public string SystemVersion { get; set; }
        public string SystemIcon { get; set; }
        public string UpdateTime { get; set; }
        public Nullable<int> State { get; set; }
    }
}
