//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USER
    {
        public int UserID { get; set; }
        public Nullable<int> LoginID { get; set; }
        public string DepartCode { get; set; }
        public string RealName { get; set; }
        public string Sex { get; set; }
        public string Phone { get; set; }
        public string QQ { get; set; }
        public string E_mail { get; set; }
        public string Wechat { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
