//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_BUG_FEEDBACK
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserIp { get; set; }
        public string BugInfo { get; set; }
        public string BugReply { get; set; }
        public Nullable<System.DateTime> FeedBackDate { get; set; }
        public string SolveMan { get; set; }
        public Nullable<System.DateTime> SolveDate { get; set; }
        public string IsShow { get; set; }
        public string State { get; set; }
    }
}
