//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zhp_AwardsLimited
    {
        public int Id { get; set; }
        public string AwardCode { get; set; }
        public Nullable<int> Gameid { get; set; }
        public string GameSoreEdge { get; set; }
        public string AwardImage { get; set; }
    }
}
