//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zhp_GameApi
    {
        public int ApiId { get; set; }
        public string ApiName { get; set; }
        public string Protocol { get; set; }
        public string ApiUrl { get; set; }
        public string ApiMethod { get; set; }
        public string RequestData { get; set; }
        public string ResponseData { get; set; }
        public string RequestContentType { get; set; }
        public string ResponseContentType { get; set; }
        public string Remark { get; set; }
    }
}
