//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zhp_GameRecord
    {
        public int ID { get; set; }
        public Nullable<int> Gameid { get; set; }
        public string PlayerScore { get; set; }
        public string PlayerNickname { get; set; }
        public string PlayerOpenId { get; set; }
        public string ComputerName { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
        public Nullable<System.DateTime> SaveTime { get; set; }
        public string PlayerPhone { get; set; }
        public string RecordType { get; set; }
        public string QRCode { get; set; }
        public string Headimgurl { get; set; }
    }
}
